# Generated by Django 3.2 on 2021-05-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('language', models.CharField(choices=[('Malyala', 'Malayalm'), ('Englis', 'English'), ('Hind', 'Hindi'), ('Unknown_Lang', 'Unknown_Lang')], default='Unknown_Lang', max_length=50)),
                ('pages', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
    ]
